library(shiny)
library(shinyjs)
library(shinytoastr)
library(shinyWidgets)
library(shinydashboard)
library(dashboardthemes)
library(shinyBS)
library(plotly)
library(DT)
source("MyButtons.R")
source("./UI/dashboard/Dashboard.R", local = TRUE)
source("./UI/home/homeUI.R", local = TRUE)
source("./UI/aboutUs.R", local = TRUE)
source("./UI/contactUs.R", local = TRUE)
library(shinydashboard)
lapply(c("ggplot2", "scales", "gplots", "lattice", "kriging", "plotly", "grid", 
         "reshape2", "xtable", "synergyfinder"), library, character.only = T)
sapply(c('CalcPlotSynergy.R', 'CalcPlotDose.R', 'getData.R'),source,.GlobalEnv)
reportspath <- "~/Desktop/test_synergyfinder/"#"/usr/srv/app/reports" # remember to change this according to environment